FROM tianon/true
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>
COPY maven_repo_server /
COPY files/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
VOLUME ["/data"]
ENTRYPOINT ["/maven_repo_server"]
